# Generated by Django 2.1.2 on 2018-10-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('world_ranking', models.IntegerField()),
                ('age', models.IntegerField()),
                ('years_pro', models.IntegerField()),
            ],
        ),
    ]
